"$schema" = 'https://starship.rs/config-schema.json'

[git_commit]
commit_hash_length = 4
tag_symbol = '🔖 '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'

[c]
format = 'via [$name $version]($style)'
